# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Service_pb2 as Service__pb2


class MicroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOnline = channel.unary_unary(
                '/MicroService/CheckOnline',
                request_serializer=Service__pb2.non.SerializeToString,
                response_deserializer=Service__pb2.Response.FromString,
                )


class MicroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MicroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOnline,
                    request_deserializer=Service__pb2.non.FromString,
                    response_serializer=Service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MicroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MicroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MicroService/CheckOnline',
            Service__pb2.non.SerializeToString,
            Service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
