# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"\x05\n\x03non\"\'\n\x08Response\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0f\n\x07process\x18\x02 \x01(\x05\x32\x30\n\x0cMicroService\x12 \n\x0b\x43heckOnline\x12\x04.non\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NON._serialized_start=17
  _NON._serialized_end=22
  _RESPONSE._serialized_start=24
  _RESPONSE._serialized_end=63
  _MICROSERVICE._serialized_start=65
  _MICROSERVICE._serialized_end=113
# @@protoc_insertion_point(module_scope)
